# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_lib', '0004_auto_20180318_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='artist',
            field=models.CharField(max_length=250),
        ),
    ]
