# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_lib', '0007_remove_albums_song_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_lib.Albums')),
                ('song_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_lib.Songs')),
            ],
        ),
        migrations.RemoveField(
            model_name='artists',
            name='album',
        ),
        migrations.DeleteModel(
            name='Artists',
        ),
    ]
